SELECT 
    TABLE_NAME, 
    COLUMN_NAME, 
    DATA_TYPE, 
    CHARACTER_MAXIMUM_LENGTH AS MAX_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('transactions_raw', 'users_raw', 'cards_raw', 'mcc_codes')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
